---
- hosts: elasticsearch
  become: true
  roles:
    - { role: SimpliField.network-hosts }
    - { role: ansiblebit.oracle-java, oracle_java_set_as_default: yes, oracle_java_version_string: "1.8.0_u152" }
    - { role: ansible-elasticsearch-2-x, es_instance_name: "{{ ansible_hostname }}", es_data_dirs: "/opt/elasticsearch/data", es_log_dir: "/opt/elasticsearch/logs", es_work_dir: "/opt/elasticsearch/temp",
      es_config: {
        node.name: "{{ ansible_hostname }}",
        cluster.name: "vodafone-cluster",
        discovery.zen.ping.unicast.hosts: "node-1:9300, node-2:9300, node-3:9300",
        http.port: 9200,
        transport.tcp.port: 9300,
        bootstrap.mlockall: true,
        discovery.zen.ping.multicast.enabled: false,
        network.host: "{{ ansible_hostname }}",
        network.bind_host: "0"
      }
    }
  vars:
    es_java_install: false
    es_version_lock: true
    es_version: "2.4.6"
    # es_major_version: "2.x"
    es_heap_size: 1g
    es_enable_xpack: false
    es_plugins_reinstall: false
    supported_xpack_features: []
    es_plugins:
        - plugin: analysis-icu
        - plugin: analysis-kuromoji
        - plugin: analysis-smartcn
        - plugin: analysis-stempel
        - plugin: lmenezes/elasticsearch-kopf
          version: 2.0
